using UnityEngine;
using UnityEngine.SceneManagement;

namespace Assets.Scripts.GameSession
{
    public class GoToScene : MonoBehaviour
    {
        public static void GoToSoloMode()
        {
            SceneManager.LoadScene("SoloGameScene", LoadSceneMode.Single);
        }
    
        public static void GoToDuoMode()
        {
            SceneManager.LoadScene("DuoGameScene", LoadSceneMode.Single);
        }
        public static void GoToMainMenu()
        {
            SceneManager.LoadScene("MainMenu", LoadSceneMode.Single);
        }
        public static void GoToDeathScreenSolo()
        {
            SceneManager.LoadScene("DeathScreen", LoadSceneMode.Single);
        }
        public static void GoToDeathScreen1VS1()
        {
            SceneManager.LoadScene("DeathScreen1VS1", LoadSceneMode.Single);
        }
    }
}